### ISSUE TITLE
Tub.listenOn() accepts strs, not unicodes

### ISSUE THREAD

**Issue by zooko** [warner/foolscap#19]
[Tub.listenOn()](https://github.com/warner/foolscap/blob/659d5003cac5d2494104f39bebedf4391ef8ed77/foolscap/pb.py#L532) accepts type str for the descriptor of how to listen. As we all know, it is an offense against decency and rightness to put human-readable data into strs. It is akin to kicking a basket of kittens. The right thing to do, of course, is to put that human-readable data into unicodes, which is like petting the kittens and giving them a saucer of warm milk.

**Comment by daira** [comment]
Twisted strports are defined to be ASCII strings.

**Comment by daira** [comment]
Note that https://github.com/warner/foolscap/commit/ccd806629a64c57f155f47ee65dbea1cf0eb26b2#diff-4c4c6a0c26553061c6ec104770e60b91R7 allows only ``[A-Za-z.0-9\-]`` in hostnames.

**Comment by warner** [comment]
Thanks to #48, this API now accepts both bytes and text.
