### ISSUE TITLE
InterfaceClass passes __module__ as __doc__

### ISSUE THREAD

**Issue by jaraco** [warner/foolscap#71]
In [this code](https://github.com/warner/foolscap/blob/845bea550447991b194ef884713a7b3be4b4a6c2/src/foolscap/remoteinterface.py#L33-L45), the `RemoteInterfaceClass.__init__` is calling the parent class, but passes `__module__` positionally. Looking at the [parent implementation](https://github.com/zopefoundation/zope.interface/blob/255db9d3c0ea7a5016e3c87644c23fca6eda9a7d/src/zope/interface/interface.py#L689-L690), that position is suited for `__doc__`. I suspect this mismatch is a bug.

**Comment by exarkun** [comment]
The linked code seems to actually be passing `__module__` around so I adjusted the ticket to reflect this
